### ISSUE TITLE
Profiler: should we add ARM MAP as alternative?

### ISSUE THREAD

**Issue by mand35** [nesi/perf-training#44]
ARM MAP can also handle python applications and is very simple to use, including visualizations, floating-point operations, memory, and line profiling

**Comment by chrisdjscott** [comment]
My preference would be to spend most of the time talking about and using the free/open source tools during the training because I think these will be the most beneficial (researchers can use them on their own machines if they want to, don't have to buy licenses, etc). 

Does MAP give some extra, useful information that the other tools do not?

Might be good to have some example output from MAP to show. We could have a section mentioning that ARM MAP is available on NeSI, similar to the [memory profiler one](https://github.com/nesi/perf-training/blob/gh-pages/_lessons/python-scatter/01-profiling.md#memory-profiler) perhaps. 

Not sure what the others will think...
